### ISSUE TITLE
Missing VelocityDepthNormalPass?

### ISSUE THREAD

**Issue by hamzakubba** [0beqz/realism-effects#1]
Hey, congrats on this release! I'm excited to give it a quick try at least, but it seems the `VelocityDepthNormalPass` is currently not being bundled/exported?

**Comment by 0beqz** [comment]
Hey, thanks!

Looks like I forgot to include it in the `index.js` file for the bundle.
It should be fixed now.

**Comment by 0beqz** [comment]
Oh well you are right, I forgot that - I've rebuild and published them as a new version.
