### ISSUE TITLE
Emissive objects?

### ISSUE THREAD

**Issue by FractalHQ** [0beqz/realism-effects#13]
Hey there!  Thanks for releasing such an amazing project!!

Are emissive textures supposed to work?  They seem to have no effect, even when creating some random messages to test it out.

I'm trying to get a video texture to reflect on the floor like in one of your old examples but nothing seems to pick up light from emissive textures.

I just want to make sure I'm not missing something!

**Comment by FractalHQ** [comment]
Hmm ok thanks!  I tried with non-animated textures, and with/without any combination of ambient/directional/environment lighting.  I will try to create a minimal reproduction example and link it here!

Perhaps it could be something in one of my custom Shader Materials or custom EffectPasses, because my scene also has this warning firing off like crazy:
`[.WebGL-0x138051ace00] GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs.`

Seems to be something regarding MRT?

**Comment by 0beqz** [comment]
Interesting, this should definitely not come up because when it comes up usually your G-buffers will be messed up and tracing won't work at all.
It has something to do with MRT but I'm not sure what could be triggering it. Is your browser version older?
