### ISSUE TITLE
poissionDenoise.frag compile error if not NORMAL_IN_RGB

### ISSUE THREAD

**Issue by Rabbid76** [0beqz/realism-effects#27]
If "NORMAL_IN_RGB" is not defined, the following line in "poissionDenoise.frag" causes a compilation error:

```glsl
float center = texel.rgb;
```

For a solution see https://github.com/0beqz/realism-effects/pull/21

**Comment by 0beqz** [comment]
Thanks, I think I'll have to rewrite the poisson denoiser as it turned more into a general GI denoiser and thus is too comprehensive for denoising AO.
