### ISSUE TITLE
NaN Propogation Error

### ISSUE THREAD

**Issue by ManishJu** [0beqz/realism-effects#31]
If you run the demo and change the model to cyber_samurai, the whole model turns black within a few seconds. 

I am running this on Mac OS 13.5.1 with M2 chip and google chrome 116.0.5845.140. Here is the 

https://github.com/0beqz/realism-effects/assets/24234466/e9a38b21-54aa-4572-b504-cffe16bd1b0a

**Comment by 0beqz** [comment]
Thanks for reporting, I was checking this out. So this used to be an issue with negative values in the temporal accumulation pass. It should be fixed now in the newer versions.
