### ISSUE TITLE
"doesnt support camera of type "perspectiveCamera"

### ISSUE THREAD

**Issue by sdraper69** [0beqz/realism-effects#32]
Hi, great work on this!

I have the following code 
```
const camera = new THREE.PerspectiveCamera(40, window.innerWidth / window.innerHeight, 0.01, 250)
const velocityDepthNormalPass = new PostProcessing.VelocityDepthNormalEffect(this.getThreeScene(), camera);
```

I am currently getting the following error

![image](https://github.com/0beqz/realism-effects/assets/25779335/4343f29e-3077-48b8-a9ad-58b04f19fb55)

I have no doubt that it is completely my problem....however, I am stumped at where to start to troubleshoot it so any suggestions would be very much appreciated. Im using Threejs r155

**Comment by 0beqz** [comment]
Hey thanks for the report, implementing OrthographicCamera support isn't so easy as quite some things need to be changed in the shader. In the newer version, OrthographicCameras are only partially supported with SSGI as in some smaller features aren't supported with it yet. So you would no longer get errors there but you still won't get the same results as with PerspectiveCameras.
So it's still an issue, I especially need to verify that at least other effects like Motion Blur support it.
