### ISSUE TITLE
Using environment map won't work in the MeshStandardMaterial after applied realism effect.

### ISSUE THREAD

**Issue by benzsuankularb** [0beqz/realism-effects#34]
Here is a minimal example.
https://codepen.io/benzsuankularb/pen/WNLzMyg

Basically, I've setup 2 canvas
One with Realism-Effect and one with normal MeshStandardMaterial.
If both canvases are enabled then the env map in MeshStandardMaterial won't work.
Both canvases didn't share any resources on the application layer.

I'm not sure if this is some issue on the Three / WebGL layer.
Or there are some modifications on the Realism-Effect applied to the MeshStandardMaterial shader.

**Comment by 0beqz** [comment]
Hey, sorry I must have overseen this issue. It's related to this one: https://github.com/0beqz/realism-effects/issues/42

It's due to a hacky way to disable a certain type of environment lighting (namely just reflections). I'm looking into it and try to use a better method.
