### ISSUE TITLE
SSR status

### ISSUE THREAD

**Issue by Supaworst** [0beqz/realism-effects#41]
Hello, my statement is more a question than an issue but i didn't know how to reach you so please, forgive me if you find this entry too much intrusive.

Basically, i can't understand the current status of your SSR effect. I mean, i've seen the other repository which at the moment seems to be deprecated due to an incompatibility with the last version of three.js.

At the moment, is the SSR effect implemented in you SSGI code? I've seen the SSR quote in the realism-effects description page but there is no description and so for me is a little bit misleading...

Anyway, thanks for your work, i really appreciate it!

**Comment by 0beqz** [comment]
Hey, all fine - thanks for the comment and sorry for the late reply!
Unfortunately there isn't much progress in this repository right now as I'm quite busy with other things and don't have as much time as I'd need to focus and work on realism-effects.

So regarding your question: this repository is focused a lot on SSGI which approximates global illumination in screen-space. The way it works is by calculating the diffuse and specular lighting in the scene. SSR calculates the specular lighting in the scene (the reflections). So SSGI is pretty much just SSR with diffuse lighting calculated as well.
So the idea is to have SSGI be an extension of SSR where it also calculates diffiuse ligthing in the scene.
This is also why there aren't many mentions of SSR in the code - SSR is just SSGI but with an extra parameter that says that we want to calculate only specular lighting.

Hope that clears that up. Although I also think I should highlight SSR more. There's also plans in optimizing it and making it more light-weight like the first version from the now deprecated repository.

**Comment by Supaworst** [comment]
Thanks for you reply, now it's clear. I'll definitely give to SSGI a try then, it seems to be what i need!
Have a nice day
