### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by vinkovsky** [0beqz/realism-effects#8]
Hello!  I have a problem on my ipad pro with m1 chip when i bring the camera close to an object
  
[Video](https://share.icloud.com/photos/0c3rli-2inufvqiwlAPdCDXlA)

**Comment by 0beqz** [comment]
Thanks for reporting. It seems to be an issue with writing negative values to the output colors especially in the tempoal reprojection pass as I've observed something similar when I was testing with negative values.
I'll check where if that could be the case and will add some guarding against negative values then.

Do you get these artifacts all the time when zooming in?

**Comment by vinkovsky** [comment]
Hello! Yes!
